name: Sync to Personal Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Organization Repository
        uses: actions/checkout@v3

      - name: Configure Git for Personal Repository
        run: |
          git config --global user.name "ericliu-12"
          git config --global user.email "133845008+alaska-summer@users.noreply.github.com"
      
      - name: Add Personal Repository as Remote
        run: |
          git clone https://ericliu-12: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@github.com/ericliu-12/project-3-team-2c.git

      - name: Copy Files to Personal Repository
        run: |
          cp -r . ../project-3-team-2c/
          cd ../project-3-team-2c/
          git add .
          git commit -m "Sync from organization repo"
          git push origin main --force

