name: Sync to Personal Repository

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "ericliu-12"
          git config --global user.email "133845008+alaska-summer@users.noreply.github.com"

      - name: Add Remote with PAT
        run: |
          git remote add personal https://ericliu-12:${{ secrets.PERSONAL_TOKEN }}@github.com/ericliu-12/project-3-team-2c.git

      - name: Push Changes
        run: |
          git push personal main --force
