name: Sync to Personal Repository

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  sync:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Organization Repository
        uses: actions/checkout@v3

      - name: Configure Git for Personal Repository
        run: |
          git config --global user.name "ericliu-12"
          git config --global user.email "133845008+alaska-summer@users.noreply.github.com"
      
      - name: Clone Personal Repository as Remote
        run: |
          git clone https://ericliu-12:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/ericliu-12/project-3-team-2c.git ../personal-repo
      
      - name: Copy Files to Personal Repository
        run: |
          rsync -av --progress --exclude .git ./ ../personal-repo/
          cd ../personal-repo/
          git add .
          git commit -m "Sync from organization repo"
          git push origin main --force
